export const teamMembers = [
  {
    img: "/assets/footer/profiles/Tracy_La.png",
    name: "Tracy La",
    emoji: "🍞",
    color: "#234036",
    title: "Co-President",
    social: "https://www.linkedin.com/in/tracy--la/",
  },
  {
    img: "/assets/footer/profiles/Angela_Cheng.png",
    name: "Angela Cheng",
    emoji: "🪷",
    color: "#9ADDFB",
    title: "Co-President",
    social: "https://www.linkedin.com/in/angela-cheng-/",
  },
  {
    img: "/assets/footer/profiles/Caitlyn_Chan.png",
    name: "Caitlyn Chan",
    emoji: "🤠",
    color: "#f5bf53",
    title: "Treasurer",
    social: "linkedin.com/in/cait-chan/",
  },
  {
    img: "/assets/footer/profiles/Jonathan_Cai.png",
    name: "Jonathan Cai",
    emoji: "🫨",
    color: "#01DACC",
    title: "HackCamp Logistics Director",
    social: "https://www.linkedin.com/in/jonathan-cai-843873314/",
  },
  {
    img: "/assets/footer/profiles/Hannah_Baek.png",
    name: "Hannah Baek",
    emoji: "😽",
    color: "#91213a",
    title: "HackCamp Logistics Coordinator",
    social: "",
  },
  {
    img: "/assets/footer/profiles/Stellar_Shar.png",
    name: "Stellar Shar",
    emoji: "🪿",
    color: "#FFC0CB",
    title: "HackCamp Logistics Coordinator",
    social: "https://www.linkedin.com/in/stellar-shar-4005b219a/",
  },
  {
    img: "/assets/footer/profiles/Roberta_Lee.png",
    name: "Roberta Lee",
    emoji: "💗",
    color: "#FFAADC",
    title: "HackCamp Logistics Coordinator",
    social: "https://www.linkedin.com/in/roberta-lee-3381662ba/",
  },
  {
    img: "/assets/footer/profiles/Anthony_Lu.png",
    name: "Anthony Lu",
    emoji: "🥳",
    color: "#ABCDEF",
    title: "HackCamp Logistics Coordinator",
    social: "https://www.linkedin.com/in/anthony-h-lu/",
  },
  {
    img: "/assets/footer/profiles/Sunny_Su.png",
    name: "Sunny Su",
    emoji: "💃",
    color: "#C6E2FF",
    title: "nwHacks Logistics Coordinator",
    social: "www.linkedin.com/in/sunnysu101",
  },
  {
    img: "/assets/footer/profiles/Jennifer_Shui.png",
    name: "Jennifer Shui",
    emoji: "🦜",
    color: "#ABCFFF",
    title: "nwHacks Logistics Director",
    social: "https://www.linkedin.com/in/jennifershui/",
  },
  {
    img: "/assets/footer/profiles/Jagathi_Moturi.png",
    name: "Jagathi Moturi",
    emoji: "🌟",
    color: "#ADD0B3",
    title: "nwHacks Logistics Coordinator",
    social: "linkedin.com/in/jagathi-moturi",
  },
  {
    img: "/assets/footer/profiles/Tiffany_Nguyen.png",
    name: "Tiffany Nguyen",
    emoji: "🐞",
    color: "#6777B6",
    title: "nwHacks Logistics Coordinator",
    social: "www.linkedin.com/in/tiffany-nguyen-14b227216",
  },
  {
    img: "/assets/footer/profiles/Connor_Young.png",
    name: "Connor Young",
    emoji: "🐶",
    color: "#9cf0ff",
    title: "nwHacks Logistics Coordinator",
    social: "linkedin.com/in/conryoung",
  },
  {
    img: "/assets/footer/profiles/Alan_Wu.png",
    name: "Alan Wu",
    emoji: "🫩",
    color: "#3eb489",
    title: "nwHacks Logistics Coordinator",
    social: "https://www.linkedin.com/in/alan-w-u/",
  },
  {
    img: "/assets/footer/profiles/Yiming_Su.png",
    name: "Yiming Su",
    emoji: "🤤",
    color: "#702963",
    title: "nwHacks Logistics Coordinator",
    social: "ysu.dev",
  },
  {
    img: "/assets/footer/profiles/Anna_Fang.png",
    name: "Anna Fang",
    emoji: "🎀",
    color: "#a76d52",
    title: "Sponsorship Director",
    social: "https://www.linkedin.com/in/anna-fang-5312a0235/",
  },
  {
    img: "/assets/footer/profiles/Fabian_Siswanto.png",
    name: "Fabian Siswanto",
    emoji: "💯",
    color: "#BFA98E",
    title: "Sponsorship Coordinator",
    social: "https://www.linkedin.com/in/fabiansiswanto/",
  },
  {
    img: "/assets/footer/profiles/Ramika_De_Silva.png",
    name: "Ramika De Silva",
    emoji: "🦥",
    color: "#91C2C1",
    title: "Sponsorship Coordinator",
    social: "https://www.linkedin.com/in/ramika-de-silva-4995b9203/",
  },
  {
    img: "/assets/footer/profiles/Simon_Chen.png",
    name: "Simon Chen",
    emoji: "🐋",
    color: "#BED6EB",
    title: "Sponsorship Coordinator",
    social: "https://www.linkedin.com/in/simonchen10/",
  },
  {
    img: "/assets/footer/profiles/Corbin_Platti.png",
    name: "Corbin Platti",
    emoji: "💰",
    color: "#fa02ee",
    title: "Sponsorship Coordinator",
    social: "https://iamcorbin.com/",
  },
  {
    img: "/assets/footer/profiles/Yash_Vasdev.png",
    name: "Yash Vasdev",
    emoji: "",
    color: "#01DACC",
    title: "Sponsorship Coordinator",
    social: "",
  },
  {
    img: "/assets/footer/profiles/Ariana_Zhassuzak.png",
    name: "Ariana Zhassuzak",
    emoji: "🦢",
    color: "#FFF0F5",
    title: "Sponsorship Coordinator",
    social: "",
  },
  {
    img: "/assets/footer/profiles/Joyce_Park.png",
    name: "Joyce Park",
    emoji: "📚",
    color: "#01DACC",
    title: "Marketing Director",
    social: "https://joycesoyeonpark.wixsite.com/joyce-park",
  },
  {
    img: "/assets/footer/profiles/Lilit_Vanyan.png",
    name: "Lilit Vanyan",
    emoji: "💋",
    color: "#F2ACB9",
    title: "Marketing Coordinator",
    social: "https://www.linkedin.com/in/lilit-vanyan-5626a2240/",
  },
  {
    img: "/assets/footer/profiles/Daisy_Han.png",
    name: "Daisy Han",
    emoji: "😛",
    color: "#A7CCFF",
    title: "Marketing Coordinator",
    social: "https://www.linkedin.com/in/daiisyhan/",
  },
  {
    img: "/assets/footer/profiles/Claudio_Pires.png",
    name: "Claudio Pires",
    emoji: "😴",
    color: "#278EF5",
    title: "Marketing Coordinator",
    social: "https://www.linkedin.com/in/claudiopires-/",
  },
  {
    img: "/assets/footer/profiles/Arnavdeep_Singh.png",
    name: "Arnavdeep Singh",
    emoji: "🐳",
    color: "#171C45",
    title: "Media Coordinator",
    social: "https://www.linkedin.com/in/arnavdeep-singh/",
  },
  {
    img: "/assets/footer/profiles/Dilna_Davi.png",
    name: "Dilna Davi",
    emoji: "🗿",
    color: "#D1FCA4",
    title: "Media Coordinator",
    social: "https://www.linkedin.com/in/dilna-davi",
  },
  {
    img: "/assets/footer/profiles/Kashish_Garg.png",
    name: "Kashish Garg",
    emoji: "🐨",
    color: "#01DACC",
    title: "Content Writer",
    social: "https://www.linkedin.com/in/kashishgarg1/",
  },
  {
    img: "/assets/footer/profiles/Elaine_Chen.png",
    name: "Elaine Chen",
    emoji: "✨",
    color: "#7f4e5a",
    title: "Design Director",
    social: "www.linkedin.com/in/elaine-c-3ab8a2231",
  },
  {
    img: "/assets/footer/profiles/Anna_Kovtunenko.png",
    name: "Anna Kovtunenko",
    emoji: "🌺",
    color: "#5e0808",
    title: "Designer",
    social: "https://www.linkedin.com/in/anna-kovtunenko/",
  },
  {
    img: "/assets/footer/profiles/Angela_Chiang.png",
    name: "Angela Chiang",
    emoji: "🫡",
    color: "#00A3FF",
    title: "Designer",
    social: "https://www.linkedin.com/in/a-hc-chiang/",
  },
  {
    img: "/assets/footer/profiles/Sarah_Chenwang.png",
    name: "Sarah Chenwang",
    emoji: "😛",
    color: "#cfe2f3",
    title: "Designer",
    social: "",
  },
  {
    img: "/assets/footer/profiles/Alexi_Manning.png",
    name: "Alexi Manning",
    emoji: "🍥",
    color: "#e7c9f5",
    title: "Designer",
    social: "",
  },
  {
    img: "/assets/footer/profiles/Ruby_Ke.png",
    name: "Ruby Ke",
    emoji: "🧸",
    color: "#FFF39C",
    title: "Designer",
    social: "https://www.linkedin.com/in/ruby-ke/",
  },
  {
    img: "/assets/footer/profiles/Geoff_Jiang.png",
    name: "Geoff Jiang",
    emoji: "🍻",
    color: "#7f11e0",
    title: "Dev Director",
    social: "https://www.linkedin.com/in/geoff-jiang/",
  },
  {
    img: "/assets/footer/profiles/Jae_Wu_Chun.png",
    name: "Jae Wu Chun",
    emoji: "",
    color: "#01DACC",
    title: "Developer",
    social: "",
  },
  {
    img: "/assets/footer/profiles/Daksh_Shahani.png",
    name: "Daksh Shahani",
    emoji: "👾",
    color: "#008581",
    title: "Developer",
    social: "https://dakshitshahani.com",
  },
  {
    img: "/assets/footer/profiles/Mackenzie_Dy.png",
    name: "Mackenzie Dy",
    emoji: "🦖",
    color: "#4E2A84",
    title: "Developer",
    social: "mackenziedy.com",
  },
  {
    img: "/assets/footer/profiles/Leia_Chen.png",
    name: "Leia Chen",
    emoji: "🦭",
    color: "#13315c",
    title: "Developer",
    social: "https://www.linkedin.com/in/leiahjchen/",
  },
  {
    img: "/assets/footer/profiles/Jasper_He.png",
    name: "Jasper He",
    emoji: "🌌",
    color: "#81b0cc",
    title: "Developer",
    social: "https://linkedin.com/in/jasperjjhe",
  },
  {
    img: "/assets/footer/profiles/Eric_Zuo.png",
    name: "Eric Zuo",
    emoji: "🎲",
    color: "#4c06c4",
    title: "Developer",
    social: "https://www.linkedin.com/in/ericzuo8/",
  },
  {
    img: "/assets/footer/profiles/Shannon_Aurelia.png",
    name: "Shannon Aurelia",
    emoji: "🩰",
    color: "#01DACC",
    title: "Product Manager",
    social: "https://www.linkedin.com/in/shannon-aurelia-s/",
  },
  {
    img: "/assets/footer/profiles/Keira_Wong.png",
    name: "Keira Wong",
    emoji: "🤍",
    color: "#000000",
    title: "EDI Director",
    social: "https://www.linkedin.com/in/keirawong/",
  },
  {
    img: "/assets/footer/profiles/Rachel_Wang.png",
    name: "Rachel Wang",
    emoji: "😑",
    color: "#CBC3E3",
    title: "Engagement Internal Director",
    social: "https://www.linkedin.com/in/rachel-wang-894626217/",
  },
  {
    img: "/assets/footer/profiles/Lincoln_Lee.png",
    name: "Lincoln Lee",
    emoji: "🍦",
    color: "#bae5f9",
    title: "Engagement Internal Coordinator",
    social: "linkedin.com/in/lincoln-seungha-lee",
  },
  {
    img: "/assets/footer/profiles/Eric_Shuai.png",
    name: "Eric Shuai",
    emoji: "🤩",
    color: "#29cff0",
    title: "Engagement Internal Coordinator",
    social: "https://www.linkedin.com/in/ericshuai",
  },
  {
    img: "/assets/footer/profiles/Gregory_Bian.png",
    name: "Gregory Bian",
    emoji: "🀄",
    color: "#0000FF",
    title: "Engagement Internal Coordinator",
    social: "https://www.linkedin.com/in/gregorybian/",
  },
  {
    img: "/assets/footer/profiles/Dhweya_Modi.png",
    name: "Dhweya Modi",
    emoji: "🥰",
    color: "#DBC8E2",
    title: "Engagement External Director",
    social: "https://www.linkedin.com/in/dhweya-modi-12428a250/",
  },
  {
    img: "/assets/footer/profiles/Daniel_Pan.png",
    name: "Daniel Pan",
    emoji: "🤠",
    color: "#01DACC",
    title: "Engagement External Coordinator",
    social: "danielpanhead.com",
  },
  {
    img: "/assets/footer/profiles/Avery_Chong.png",
    name: "Avery Chong",
    emoji: "☹️",
    color: "#414141",
    title: "Engagement External Coordinator",
    social: "",
  },
  {
    img: "/assets/footer/profiles/Wakana_Kuwayama.png",
    name: "Wakana Kuwayama",
    emoji: "🫧",
    color: "#A8D5BA",
    title: "Engagement External Coordinator",
    social: "www.linkedin.com/in/wakana-k",
  },
];
